- name: Copying the hosts file to all the nodes
  copy: src=/etc/hosts dest=/etc/hosts

- name: Setting up the rpository configuration
  yum_repository: 
      name: CSF-BANA 
      description: "CSF Bana repository" 
      file: csf-bana-repo
      baseurl: "{{ CSF_CDLK_CLUSTER_CONFIG.repo_url }}"
      gpgcheck: no
      state: present

- name: Upgrading all the packages
  yum: name=* state=latest

#- name: Disabling the Firewall 
#  service: name=firewalld state=stopped enabled=no

- name: Installing the prerequisite Packages on all the nodes
  yum: name=java  state=latest 

- name: Getting the java Home Path
  shell: readlink -f /usr/bin/java | sed "s:bin/java::"
  register: javahomeout

- name: Setting the JAVA_HOME environment variable in profile file
  lineinfile: path=/etc/profile line="JAVA_HOME={{ javahomeout.stdout }}" state=present

- name: Setting the kernel parameters in the systemctl.conf
  sysctl: name=vm.swappiness value=0  state=present

- name: Disabling the selinux on all the servers
  selinux: state=disabled
  notify: 
      - Restart server
      - Wait for server to restart
