#!/usr/bin/python

# import some python modules that we'll use.  These are all
# available in Python's core
from ansible.module_utils.basic import AnsibleModule
from copy import deepcopy
import datetime
import sys
import json
import yaml
import os
import shlex

module = AnsibleModule(
     argument_spec = dict(
         data=dict(required=False),
         file=dict(required=True)
             )
          )
#print module.argument_spec
arguments = module.params['data']
file=module.params['file']
data=eval(arguments)
with open(file, 'w') as outfile:
        json.dump({'aws_data': deepcopy(data)},outfile,indent=4,separators=(',',':'))
print(json.dumps({"data": arguments}))
