---
- include_vars: ../../../vars.yaml

#################################################

- name: Add the KERBEROS Service to cluster
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/services/KERBEROS
       method=POST
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202


- name: Add the KERBEROS_CLIENT component to the KERBEROS service
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/services/KERBEROS/components/KERBEROS_CLIENT
       method=POST
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       status_code=200,201,202

- name: Create and set KERBEROS service configurations
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body="{{ lookup('file','cdlk_kerberos_base.json') | to_json }}"
       body_format=json
       status_code=200,201,202
       return_content=yes

#################################################

- name: Create the KERBEROS_CLIENT host components (once for each host, replacing HOST_NAME)
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/hosts?Hosts/host_name={{ item }}
       method=POST
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body='{"host_components":[{"HostRoles":{"component_name":"KERBEROS_CLIENT"}}]}'
       status_code=200,201,202
  with_items:
   - "{{ groups['ambari_agent'] }}"
  

################################################
  
- name: Install the KERBEROS service and components
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/services/KERBEROS
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body=' {"RequestInfo":{"context":"Install Kerberos Client"},"Body":{"ServiceInfo":{"state":"INSTALLED"}}}'
       status_code=202
       return_content=yes
  register: kerberos_install

- name: Displaying the kerberos_install Request ID
  debug:
    msg: "Status Check of kerberos_install with request ID - {{ (kerberos_install.content|from_json)['Requests']['id'] }}"

- name: Status Check of kerberos_install
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (kerberos_install.content|from_json)['Requests']['id'] }}"

- name: Displaying the status of kerberos_install
  debug:
    msg: "kerberos_install is  {{ (status_response['results'][0]['content']|from_json)['Requests']['request_status'] }}"

- name: Polling the Status of kerberos_install
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (kerberos_install.content|from_json)['Requests']['id'] }}"
  until: (((status_response['content']|from_json)['Requests']['request_status']) == "FAILED") or (((status_response['content']|from_json)['Requests']['request_status']) == "COMPLETED")
  retries: 10
  delay: 15    
 
- name: Stop all services #this failed
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/services
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body='{"RequestInfo":{"context":"Stop Service"},"Body":{"ServiceInfo":{"state":"INSTALLED"}}}'
       status_code=202
       return_content=yes
  register: stop_services

- name: Displaying the stop_services Request ID
  debug:
    msg: "Status Check of stop_services with request ID - {{ (stop_services.content|from_json)['Requests']['id'] }}"

- name: Status Check of stop_services
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (stop_services.content|from_json)['Requests']['id'] }}"

- name: Displaying the status of stop_services
  debug:
    msg: "stop_services is  {{ (status_response['results'][0]['content']|from_json)['Requests']['request_status'] }}"
    
 
- name: Polling the Status of stop_services
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (stop_services.content|from_json)['Requests']['id'] }}"
  until: (((status_response['content']|from_json)['Requests']['request_status']) == "FAILED") or (((status_response['content']|from_json)['Requests']['request_status']) == "COMPLETED")
  retries: 50
  delay: 10
  
- name: Enable Kerberos
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body=" {{ lookup('file','cdlk_kerberos_base_payload.json') | to_json }}"
       body_format=json
       status_code=202
       return_content=yes
  register: enable_kerberos

- name: Displaying the enable_kerberos Request ID
  debug:
    msg: "Status Check of enable_kerberos with request ID - {{ (enable_kerberos.content|from_json)['Requests']['id'] }}"

- name: Status Check of enable_kerberos
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (enable_kerberos.content|from_json)['Requests']['id'] }}"

- name: Displaying the status of enable_kerberos
  debug:
    msg: "enable_kerberos is  {{ (status_response['results'][0]['content']|from_json)['Requests']['request_status'] }}"
    
 
- name: Polling the Status of enable_kerberos
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (enable_kerberos.content|from_json)['Requests']['id'] }}"
  until: (((status_response['content']|from_json)['Requests']['request_status']) == "FAILED") or (((status_response['content']|from_json)['Requests']['request_status']) == "COMPLETED")
  retries: 50
  delay: 10
  

- name: Start all services
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/services
       method=PUT
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       body='{"RequestInfo":{"context":"Start all Services"},"Body":{"ServiceInfo":{"state":"STARTED"}}}'
       status_code=202
       return_content=yes
  register: start_services

- name: Displaying the start_services Request ID
  debug:
    msg: "Status Check of start_services with request ID - {{ (start_services.content|from_json)['Requests']['id'] }}"

- name: Status Check of start_services
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (start_services.content|from_json)['Requests']['id'] }}"

- name: Displaying the status of start_services
  debug:
    msg: "start_services is  {{ (status_response['results'][0]['content']|from_json)['Requests']['request_status'] }}"
    
 
- name: Polling the Status of start_services
  uri: url=http://{{ AMBARI.AMBARI_SERVER.host }}:8080/api/v1/clusters/{{ CSF_CDLK_CLUSTER_CONFIG.cluster_name }}/requests/{{ item }}
       method=GET
       force_basic_auth=yes
       user=admin
       password=admin
       HEADER_X-Requested-By="ambari"
       return_content=yes
  register: status_response
  with_items: "{{ (start_services.content|from_json)['Requests']['id'] }}"
  until: (((status_response['content']|from_json)['Requests']['request_status']) == "FAILED") or (((status_response['content']|from_json)['Requests']['request_status']) == "COMPLETED")
  retries: 50
  delay: 10
